In [116]:
import pandas as pd                                                  #Importem la llibreria pandas (pd).
dades = pd.read_csv('time_series_covid19_deaths_US.csv')  
                                   
dades = pd.DataFrame(dades)  

dades

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20,10/12/20,10/13/20,10/14/20,10/15/20,10/16/20
0,84001001,US,USA,840,1001.0,Autauga,Alabama,US,32.539527,-86.644082,...,27,28,28,28,28,28,28,28,28,28
1,84001003,US,USA,840,1003.0,Baldwin,Alabama,US,30.727750,-87.722071,...,56,64,64,65,65,65,65,66,66,67
2,84001005,US,USA,840,1005.0,Barbour,Alabama,US,31.868263,-85.387129,...,7,9,9,9,9,9,9,9,9,9
3,84001007,US,USA,840,1007.0,Bibb,Alabama,US,32.996421,-87.125115,...,10,12,12,12,12,12,12,13,13,13
4,84001009,US,USA,840,1009.0,Blount,Alabama,US,33.982109,-86.567906,...,16,16,16,16,16,16,16,23,23,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,84056039,US,USA,840,56039.0,Teton,Wyoming,US,43.935225,-110.589080,...,1,1,1,1,1,1,1,1,1,1
3336,84056041,US,USA,840,56041.0,Uinta,Wyoming,US,41.287818,-110.547578,...,2,2,2,2,2,2,2,2,2,2
3337,84090056,US,USA,840,90056.0,Unassigned,Wyoming,US,0.000000,0.000000,...,0,1,1,1,1,0,0,0,0,0
3338,84056043,US,USA,840,56043.0,Washakie,Wyoming,US,43.904516,-107.680187,...,6,6,6,6,6,6,7,7,7,7
3339,84056045,US,USA,840,56045.0,Weston,Wyoming,US,43.839612,-104.567488,...,0,0,0,0,0,0,0,0,0,0

In [117]:
dades2=dades[dades["Province_State"] == "North Carolina"]

dades2

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20,10/12/20,10/13/20,10/14/20,10/15/20,10/16/20
1964,84037001,US,USA,840,37001.0,Alamance,North Carolina,US,36.043470,-79.399761,...,59,59,59,59,59,59,59,59,59,59
1965,84037003,US,USA,840,37003.0,Alexander,North Carolina,US,35.922380,-81.177519,...,8,8,8,8,8,8,8,8,9,9
1966,84037005,US,USA,840,37005.0,Alleghany,North Carolina,US,36.493609,-81.128570,...,0,0,0,1,1,1,1,1,1,1
1967,84037007,US,USA,840,37007.0,Anson,North Carolina,US,34.974032,-80.099533,...,6,6,6,6,6,6,8,8,8,8
1968,84037009,US,USA,840,37009.0,Ashe,North Carolina,US,36.432962,-81.498627,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2061,84037191,US,USA,840,37191.0,Wayne,North Carolina,US,35.364381,-78.000273,...,73,73,74,74,74,74,74,75,76,76
2062,84037193,US,USA,840,37193.0,Wilkes,North Carolina,US,36.208413,-81.162329,...,35,35,35,35,35,35,36,36,36,36
2063,84037195,US,USA,840,37195.0,Wilson,North Carolina,US,35.706255,-77.917978,...,57,58,58,58,58,58,61,61,62,62
2064,84037197,US,USA,840,37197.0,Yadkin,North Carolina,US,36.162226,-80.662394,...,9,9,9,9,9,9,9,9,9,9
2065,84037199,US,USA,840,37199.0,Yancey,North Carolina,US,35.900792,-82.312372,...,0,0,0,0,0,0,0,0,0,0

In [118]:
dades2 = dades2.drop(columns = ["UID", "iso2", "iso3", "code3", "FIPS", "Country_Region", "Population", "Combined_Key"])
dades2

,Admin2,Province_State,Lat,Long_,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20,10/12/20,10/13/20,10/14/20,10/15/20,10/16/20
1964,Alamance,North Carolina,36.043470,-79.399761,0,0,0,0,0,0,...,59,59,59,59,59,59,59,59,59,59
1965,Alexander,North Carolina,35.922380,-81.177519,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,9,9
1966,Alleghany,North Carolina,36.493609,-81.128570,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
1967,Anson,North Carolina,34.974032,-80.099533,0,0,0,0,0,0,...,6,6,6,6,6,6,8,8,8,8
1968,Ashe,North Carolina,36.432962,-81.498627,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2061,Wayne,North Carolina,35.364381,-78.000273,0,0,0,0,0,0,...,73,73,74,74,74,74,74,75,76,76
2062,Wilkes,North Carolina,36.208413,-81.162329,0,0,0,0,0,0,...,35,35,35,35,35,35,36,36,36,36
2063,Wilson,North Carolina,35.706255,-77.917978,0,0,0,0,0,0,...,57,58,58,58,58,58,61,61,62,62
2064,Yadkin,North Carolina,36.162226,-80.662394,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
2065,Yancey,North Carolina,35.900792,-82.312372,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [123]:
for i in dades2:
    print (dades2[i]["Lat"] )

KeyError: 'Lat'

In [102]:
data = "4/4/20"

In [76]:
def muertos_dia(d):
    x=list(dades2.columns)
    y=x.index(d)
    return dades2.iloc[:,[0,y]]

In [101]:
# import pygame
import pygame

# initialize game engine
pygame.init()

window_width=700
window_height=700

animation_increment=10
clock_tick_rate=20

# Open a window
size = (900, 700)
screen = pygame.display.set_mode(size)

# Set title to the window
pygame.display.set_caption("Covid USA")

dead=False

clock = pygame.time.Clock()
background_image = pygame.image.load("NC.jpg").convert()

while(dead==False):
    background_image= pygame.transform.smoothscale(background_image, (900,700))
    
    for event in pygame.event.get():

        if event.type == pygame.MOUSEBUTTONUP:
            start = event.pos
            print("start",start)

        if event.type == pygame.QUIT:
            dead = True
    screen.blit(background_image, [0, 0])
    for i in Diccionari:
        pygame.draw.circle(screen,(155,0,0),Diccionari[i],(1))
    pygame.display.flip()
    pygame.display.update()
    clock.tick(clock_tick_rate)

In [104]:
pygame.quit()

In [97]:
Diccionari = {
"Cherokee":[67,382]
,"Clay":[102,392]
,"Macon":[130,380]
,"Jackson":[159,366]
,"Transylvania":[189,378]
,"Henderson":[215,365]
,"Polk":[242,369]
,"Rutherford":[268,358]
,"Cleveland":[301,366]
,"Gaston":[331,368]
,"Lincon":[327,349]
,"Mecklenburg":[362,377]
,"Union":[386,404]
,"Cabarrus":[386,358]
,"Anson":[427,402]
,"Stanly":[414,364]
,"Montgomery":[445,366]
,"Richmond":[461,401]
,"Moore":[484,365]
,"Scotland":[485,418]
,"Hoke":[504,396]
,"Cumberland":[541,391]
,"Robeson":[515,439]
,"Bladen":[563,440]
,"Columbus":[553,479]
,"Brunkswick":[595,503]
,"New Hanover":[629,479]
,"Pender":[625,448]
,"Sampson":[583,397]
,"Duplin":[622,401]
,"Graham":[92,358]
,"Swain":[127,344]
,"Haywood":[171,339]
,"Madison":[197,305]
,"Buncombe":[211,332]
,"Yancey":[234,302]
,"Mitchell":[241,281]
,"McDowell":[253,326]
,"Burke":[283,320]
,"Avery":[266,280]
,"Caldwell":[297,296]
,"Catawba":[325,327]
,"Alexander":[331,300]
,"Iredell":[357,311]
,"Rowan":[384,329]
,"Davie":[385,298]
,"Davidson":[416,311]
,"Randolph":[450,322]
,"Chatham":[495,322]
,"Lee":[511,348]
,"Harnett":[535,360]
,"Wake":[551,315]
,"Johnston":[582,340]
,"Wayne":[613,356]
,"Onslow":[669,426]
,"Jones":[668,388]
,"Carteret":[746,409]
,"Craven":[689,373]
,"Lenoir":[645,373]
,"Grenee":[641,342]
,"Pamlico":[721,381]
,"Watunga":[283,264]
,"Ashe":[301,244]
,"Wilkes":[333,266]
,"Allerghany":[335,237]
,"Yadkin":[375,274]
,"Surry":[372,244]
,"Forsith":[412,276]
,"Stokes":[413,250]
,"Guilford":[453,283]
,"Rockingham":[453,247]
,"Caswell":[491,246]
,"Alamance":[488,288]
,"Orange":[513,282]
,"Durham":[535,287]
,"Person":[525,248]
,"Granville":[551,256]
,"Vance":[575,248]
,"Franklin":[587,278]
,"Warren":[601,246]
,"Nash":[613,292]
,"Wilson":[621,318]
,"Halifax":[633,256]
,"Edgecombe":[647,298]
,"Pitt":[667,327]
,"Beaufort":[714,337]
,"Hyde":[770,338]
,"Dare":[803,304]
,"Tyrell":[770,300]
,"Martin":[691,308]
,"Northampton":[667,240]
,"Hertford":[696,244]
,"Bertie":[701,274]
,"Washington":[741,300]
,"Chowan":[731,271]
,"Gates":[724,233]
,"Perquimans":[746,256]
,"Pasquotank":[760,247]
,"Camden":[758,230]
,"Currituck":[788,239]}